### ISSUE TITLE
Large file not used

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/zeleriscarrier#5]
Hi,

If you do not use the file */views/img/Imagen Zeleris.jpg*, please remove it.

This file is really big, which makes the module heavier (and in consequence more difficult to download). I just tried to use the module on a shop with a small configuration, and the upload failed with the following error: **File too large**.

**Comment by jcriadop** [comment]
Hi, image deleted

**Comment by Quetzacoalt91** [comment]
Thanks, the PR #4 has been merged so we can close this issue.
